import { NextRequest, NextResponse } from "next/server";

// Clean, unique list of major stocks organized by sector
// Total: 200+ unique stocks across various sectors
const ALL_STOCKS = [
  // Technology - Software & Services
  "AAPL",
  "MSFT",
  "GOOGL",
  "META",
  "NVDA",
  "ADBE",
  "CRM",
  "ORCL",
  "SAP",
  "WDAY",
  "ZS",
  "OKTA",
  "CRWD",
  "NET",
  "DDOG",
  "PLTR",
  "SNOW",
  "MDB",
  "ESTC",
  "TEAM",
  "ZM",
  "SHOP",
  "SQ",
  "ROKU",
  "SPOT",
  "UBER",
  "LYFT",
  "DASH",
  "ABNB",
  "PINS",
  "SNAP",
  "TWTR",
  "NFLX",
  "AMD",
  "INTC",
  "QCOM",
  "AVGO",
  "MU",
  "AMAT",
  "LRCX",
  "KLAC",
  "ASML",
  "TSM",
  "ADI",
  "TXN",
  "MCHP",
  "ON",
  "SWKS",
  "QRVO",
  "CRUS",
  "ANSS",
  "FTNT",
  "PAYX",
  "CTSH",
  "CDNS",

  // E-commerce & Consumer Tech
  "AMZN",
  "TSLA",
  "NKE",
  "UA",
  "LULU",
  "SBUX",
  "MCD",
  "YUM",
  "CMG",
  "DPZ",

  // Financial Services
  "JPM",
  "BAC",
  "WFC",
  "GS",
  "MS",
  "C",
  "USB",
  "PNC",
  "TFC",
  "COF",
  "AXP",
  "DFS",
  "V",
  "MA",
  "PYPL",
  "BLK",
  "SCHW",
  "ETFC",
  "AMTD",
  "IBKR",
  "LPLA",
  "RJF",
  "SPGI",
  "PLD",
  "T",
  "MMC",
  "AJRD",
  "KTOS",
  "ADP",
  "AON",
  "AIG",
  "ALL",
  "AFL",
  "MET",
  "PRU",
  "TRV",
  "PGR",
  "CB",
  "ACE",
  "CNA",
  "HIG",
  "PFG",
  "LNC",
  "UNM",
  "AEG",

  // Healthcare & Pharmaceuticals
  "JNJ",
  "PFE",
  "UNH",
  "ABT",
  "TMO",
  "DHR",
  "LLY",
  "ABBV",
  "BMY",
  "AMGN",
  "GILD",
  "REGN",
  "VRTX",
  "BIIB",
  "ALXN",
  "INCY",
  "EXEL",
  "SGEN",
  "MRNA",
  "BNTX",
  "NVAX",
  "ISRG",
  "ABMD",

  // Consumer Goods & Retail
  "PG",
  "KO",
  "PEP",
  "WMT",
  "HD",
  "LOW",
  "COST",
  "TJX",
  "BKNG",
  "MAR",
  "HLT",
  "CCL",
  "NCLH",
  "RCL",
  "DIS",
  "VZ",
  "CMCSA",

  // Energy & Utilities
  "XOM",
  "CVX",
  "COP",
  "EOG",
  "SLB",
  "HAL",
  "BKR",
  "NOV",
  "FTI",
  "WFT",
  "OXY",
  "PXD",
  "DVN",
  "HES",
  "MPC",
  "PSX",
  "VLO",
  "ENB",
  "TRP",
  "KMI",
  "EPD",
  "ET",
  "WMB",

  // Industrial & Manufacturing
  "CAT",
  "DE",
  "BA",
  "LMT",
  "RTX",
  "GD",
  "NOC",
  "LHX",
  "TDG",
  "HEI",
  "TXT",
  "GE",
  "MMM",
  "EMR",
  "ETN",
  "ROK",
  "DOV",
  "XYL",
  "IEX",
  "AME",
  "FLS",
  "UPS",
  "IBM",

  // International Stocks
  "NOVO",
  "NESTLE",
  "ROCHE",
  "NOVARTIS",
  "SIE",
  "BMW",
  "VW",
  "BAYER",
  "ALLIANZ",
  "DEUTSCHE",
  "CREDIT",
  "UBS",
  "SMIC",
  "UMC",
  "STM",
  "NXP",
];

// Company name mapping for better display
const COMPANY_NAMES: Record<string, string> = {
  AAPL: "Apple Inc.",
  MSFT: "Microsoft Corporation",
  GOOGL: "Alphabet Inc. (Google)",
  META: "Meta Platforms Inc.",
  NVDA: "NVIDIA Corporation",
  AMZN: "Amazon.com Inc.",
  TSLA: "Tesla Inc.",
  JPM: "JPMorgan Chase & Co.",
  JNJ: "Johnson & Johnson",
  PG: "Procter & Gamble Co.",
  UNH: "UnitedHealth Group Inc.",
  HD: "Home Depot Inc.",
  MA: "Mastercard Inc.",
  V: "Visa Inc.",
  DIS: "Walt Disney Co.",
  PYPL: "PayPal Holdings Inc.",
  ADBE: "Adobe Inc.",
  CRM: "Salesforce Inc.",
  NKE: "Nike Inc.",
  WMT: "Walmart Inc.",
  KO: "Coca-Cola Co.",
  PEP: "PepsiCo Inc.",
  ABT: "Abbott Laboratories",
  TMO: "Thermo Fisher Scientific",
  AVGO: "Broadcom Inc.",
  COST: "Costco Wholesale Corp.",
  ACN: "Accenture PLC",
  DHR: "Danaher Corporation",
  LLY: "Eli Lilly and Company",
  VZ: "Verizon Communications",
  CMCSA: "Comcast Corporation",
  PFE: "Pfizer Inc.",
  TXN: "Texas Instruments",
  QCOM: "Qualcomm Inc.",
  HON: "Honeywell International",
  UPS: "United Parcel Service",
  LOW: "Lowe's Companies",
  RTX: "Raytheon Technologies",
  IBM: "International Business Machines",
  CAT: "Caterpillar Inc.",
  GS: "Goldman Sachs Group",
  MS: "Morgan Stanley",
  AXP: "American Express Co.",
  SPGI: "S&P Global Inc.",
  PLD: "Prologis Inc.",
  T: "AT&T Inc.",
  DE: "Deere & Company",
  GE: "General Electric Co.",
  BA: "Boeing Co.",
  MMC: "Marsh & McLennan Companies",
  TJX: "TJX Companies Inc.",
  BKNG: "Booking Holdings Inc.",
  ADI: "Analog Devices Inc.",
  GILD: "Gilead Sciences Inc.",
  ISRG: "Intuitive Surgical Inc.",
  VRTX: "Vertex Pharmaceuticals",
  REGN: "Regeneron Pharmaceuticals",
  ABMD: "Abiomed Inc.",
  KLAC: "KLA Corporation",
  LRCX: "Lam Research Corporation",
  MU: "Micron Technology Inc.",
  AMAT: "Applied Materials Inc.",
  CDNS: "Cadence Design Systems",
  SNPS: "Synopsys Inc.",
  ANSS: "ANSYS Inc.",
  FTNT: "Fortinet Inc.",
  PAYX: "Paychex Inc.",
  CTSH: "Cognizant Technology Solutions",
  ORCL: "Oracle Corporation",
  SAP: "SAP SE",
  WDAY: "Workday Inc.",
  ZS: "Zscaler Inc.",
  OKTA: "Okta Inc.",
  CRWD: "CrowdStrike Holdings Inc.",
  NET: "Cloudflare Inc.",
  DDOG: "Datadog Inc.",
  PLTR: "Palantir Technologies Inc.",
  SNOW: "Snowflake Inc.",
  MDB: "MongoDB Inc.",
  ESTC: "Elastic N.V.",
  TEAM: "Atlassian Corporation",
  ZM: "Zoom Video Communications",
  SHOP: "Shopify Inc.",
  SQ: "Block Inc. (Square)",
  ROKU: "Roku Inc.",
  SPOT: "Spotify Technology S.A.",
  UBER: "Uber Technologies Inc.",
  LYFT: "Lyft Inc.",
  DASH: "DoorDash Inc.",
  ABNB: "Airbnb Inc.",
  PINS: "Pinterest Inc.",
  SNAP: "Snap Inc.",
  TWTR: "Twitter Inc.",
  NFLX: "Netflix Inc.",
  AMD: "Advanced Micro Devices Inc.",
  INTC: "Intel Corporation",
  ASML: "ASML Holding N.V.",
  TSM: "Taiwan Semiconductor Manufacturing",
  STM: "STMicroelectronics N.V.",
  NXP: "NXP Semiconductors N.V.",
  BAC: "Bank of America Corp.",
  WFC: "Wells Fargo & Company",
  C: "Citigroup Inc.",
  USB: "U.S. Bancorp",
  PNC: "PNC Financial Services Group",
  TFC: "Truist Financial Corporation",
  COF: "Capital One Financial Corp.",
  DFS: "Discover Financial Services",
  BLK: "BlackRock Inc.",
  SCHW: "Charles Schwab Corporation",
  ETFC: "E*TRADE Financial Corporation",
  AMTD: "TD Ameritrade Holding Corporation",
  IBKR: "Interactive Brokers Group Inc.",
  LPLA: "LPL Financial Holdings Inc.",
  RJF: "Raymond James Financial Inc.",
  AJRD: "Aerojet Rocketdyne Holdings Inc.",
  KTOS: "Kratos Defense & Security Solutions",
  ABBV: "AbbVie Inc.",
  BMY: "Bristol-Myers Squibb Company",
  AMGN: "Amgen Inc.",
  BIIB: "Biogen Inc.",
  ALXN: "Alexion Pharmaceuticals Inc.",
  INCY: "Incyte Corporation",
  EXEL: "Exelixis Inc.",
  SGEN: "Seagen Inc.",
  MRNA: "Moderna Inc.",
  BNTX: "BioNTech SE",
  NVAX: "Novavax Inc.",
  LULU: "Lululemon Athletica Inc.",
  SBUX: "Starbucks Corporation",
  MCD: "McDonald's Corporation",
  YUM: "Yum! Brands Inc.",
  CMG: "Chipotle Mexican Grill Inc.",
  DPZ: "Domino's Pizza Inc.",
  MAR: "Marriott International Inc.",
  HLT: "Hilton Worldwide Holdings Inc.",
  CCL: "Carnival Corporation",
  NCLH: "Norwegian Cruise Line Holdings",
  RCL: "Royal Caribbean Cruises Ltd.",
  XOM: "Exxon Mobil Corporation",
  CVX: "Chevron Corporation",
  COP: "ConocoPhillips",
  EOG: "EOG Resources Inc.",
  SLB: "Schlumberger Limited",
  HAL: "Halliburton Company",
  BKR: "Baker Hughes Company",
  NOV: "National Oilwell Varco Inc.",
  FTI: "TechnipFMC PLC",
  WFT: "Weatherford International PLC",
  OXY: "Occidental Petroleum Corporation",
  PXD: "Pioneer Natural Resources Company",
  DVN: "Devon Energy Corporation",
  HES: "Hess Corporation",
  MPC: "Marathon Petroleum Corporation",
  PSX: "Phillips 66",
  VLO: "Valero Energy Corporation",
  ENB: "Enbridge Inc.",
  TRP: "TC Energy Corporation",
  KMI: "Kinder Morgan Inc.",
  EPD: "Enterprise Products Partners L.P.",
  ET: "Energy Transfer L.P.",
  WMB: "Williams Companies Inc.",
  LMT: "Lockheed Martin Corporation",
  GD: "General Dynamics Corporation",
  NOC: "Northrop Grumman Corporation",
  LHX: "L3Harris Technologies Inc.",
  TDG: "TransDigm Group Incorporated",
  HEI: "Heico Corporation",
  TXT: "Textron Inc.",
  MMM: "3M Company",
  EMR: "Emerson Electric Co.",
  ETN: "Eaton Corporation PLC",
  ROK: "Rockwell Automation Inc.",
  DOV: "Dover Corporation",
  XYL: "Xylem Inc.",
  IEX: "IDEX Corporation",
  AME: "AMETEK Inc.",
  FLS: "Flowserve Corporation",
  NOVO: "Novo Nordisk A/S",
  NESTLE: "Nestlé S.A.",
  ROCHE: "Roche Holding AG",
  NOVARTIS: "Novartis AG",
  SIE: "Siemens AG",
  BMW: "BMW AG",
  VW: "Volkswagen AG",
  BAYER: "Bayer AG",
  ALLIANZ: "Allianz SE",
  DEUTSCHE: "Deutsche Bank AG",
  CREDIT: "Credit Suisse Group AG",
  UBS: "UBS Group AG",
  SMIC: "Semiconductor Manufacturing International",
  UMC: "United Microelectronics Corporation",
};

// Ensure no duplicates in the stock list
const UNIQUE_STOCKS = [...new Set(ALL_STOCKS)];

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get("page") || "1");
    const search = searchParams.get("search") || "";
    const limit = parseInt(searchParams.get("limit") || "20");

    // Filter stocks based on search query
    let filteredStocks = UNIQUE_STOCKS;
    if (search) {
      filteredStocks = UNIQUE_STOCKS.filter((stock) =>
        stock.toLowerCase().includes(search.toLowerCase())
      );
    }

    // Calculate pagination
    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;
    const paginatedStocks = filteredStocks.slice(startIndex, endIndex);

    // Add company names to the response
    const stocksWithNames = paginatedStocks.map((symbol) => ({
      symbol,
      companyName: COMPANY_NAMES[symbol] || `${symbol} Corporation`,
    }));

    // Simulate API delay for better UX
    await new Promise((resolve) => setTimeout(resolve, 100));

    return NextResponse.json({
      stocks: stocksWithNames,
      total: filteredStocks.length,
      page,
      limit,
      hasMore: endIndex < filteredStocks.length,
    });
  } catch (error) {
    console.error("Error fetching stocks:", error);
    return NextResponse.json(
      { error: "Failed to fetch stocks" },
      { status: 500 }
    );
  }
}
